import { Head } from 'vite-react-ssg';
import { LegalLayout, type LegalSection } from '../../components/legal/LegalLayout';
import { CONTACT_EMAIL } from '../../lib/config';

const sections: LegalSection[] = [
  {
    id: 'acceptance',
    heading: 'Acceptance of terms',
    body: (
      <>
        <p>
          These Terms of Service ("Terms") govern your access to and use of
          the Roshan AI website, the ShifaMind platform, and any related
          services (collectively, the "Services") operated by Roshan AI LLC
          ("Roshan AI," "we," "us").
        </p>
        <p>
          By accessing or using the Services, you agree to be bound by these
          Terms. If you don't agree, don't use the Services. If you are
          accepting these Terms on behalf of an organization, you represent
          that you have authority to bind that organization.
        </p>
      </>
    ),
  },
  {
    id: 'services',
    heading: 'The Services',
    body: (
      <>
        <p>
          Roshan AI provides clinical-AI infrastructure and software products,
          including the ShifaMind product, that produce predictions, structured
          outputs, and decision-support information from clinical data. The
          Services are offered to clinicians, researchers, integrators, and
          health organizations for evaluation and production use under
          applicable agreements.
        </p>
      </>
    ),
  },
  {
    id: 'clinical-disclaimer',
    heading: 'Clinical-use disclaimer',
    body: (
      <>
        <p>
          <strong>The Services are not a medical device.</strong> They do not
          render a diagnosis, prescribe treatment, or replace the judgment of a
          licensed clinician. Outputs are intended to support — not replace —
          clinical decision-making.
        </p>
        <p>
          You agree that any output generated by the Services will be reviewed
          by an appropriately licensed clinician before being relied upon for
          patient care, billing, or coding purposes. Roshan AI is not
          responsible for clinical, billing, or coding outcomes that result
          from unsupervised use of Service outputs.
        </p>
      </>
    ),
  },
  {
    id: 'accounts',
    heading: 'Accounts',
    body: (
      <>
        <p>
          To use certain features you must create an account. You are
          responsible for maintaining the confidentiality of your credentials
          and for all activity that occurs under your account. Notify us
          immediately at{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-accent hover:underline">
            {CONTACT_EMAIL}
          </a>{' '}
          of any unauthorized use.
        </p>
      </>
    ),
  },
  {
    id: 'acceptable-use',
    heading: 'Acceptable use',
    body: (
      <>
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1.5 pl-5">
          <li>
            Use the Services to violate any law, regulation, or third-party
            right (including HIPAA, applicable data-protection laws, or other
            health-information regulations);
          </li>
          <li>
            Reverse engineer, decompile, or attempt to extract the source code
            or underlying models of the Services, except as permitted by law;
          </li>
          <li>
            Use the Services to harass, defraud, or harm any person;
          </li>
          <li>
            Submit content that infringes intellectual property, contains
            malware, or is otherwise unlawful;
          </li>
          <li>
            Probe, scan, or test the vulnerability of any system or network
            associated with the Services without our prior written permission;
          </li>
          <li>
            Use the Services to train, fine-tune, or evaluate a competing
            product without our prior written agreement.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'customer-content',
    heading: 'Customer content',
    body: (
      <>
        <p>
          You retain ownership of content you submit to the Services
          ("Customer Content"). You grant Roshan AI a limited, non-exclusive,
          worldwide license to process Customer Content solely to provide the
          Services to you and to comply with law.
        </p>
        <p>
          We do not use Customer Content to train our base models without your
          explicit written consent. Any opt-in research arrangement will be
          governed by a separate written agreement.
        </p>
      </>
    ),
  },
  {
    id: 'phi',
    heading: 'PHI and the BAA',
    body: (
      <>
        <p>
          If you intend to process Protected Health Information (PHI) through
          the Services, you must enter into a Business Associate Agreement
          (BAA) with Roshan AI before doing so. The BAA, together with these
          Terms, governs the handling of PHI. In the event of a conflict
          between the BAA and these Terms with respect to PHI, the BAA
          controls.
        </p>
      </>
    ),
  },
  {
    id: 'intellectual-property',
    heading: 'Intellectual property',
    body: (
      <>
        <p>
          The Services, including all software, models, content, and
          documentation, are owned by Roshan AI or its licensors and are
          protected by intellectual-property laws. Subject to your compliance
          with these Terms, we grant you a limited, revocable, non-exclusive,
          non-transferable license to access and use the Services for their
          intended purpose.
        </p>
        <p>
          We welcome feedback and suggestions; you grant us a perpetual,
          royalty-free license to use any such feedback to improve the
          Services, without obligation to you.
        </p>
      </>
    ),
  },
  {
    id: 'fees',
    heading: 'Fees',
    body: (
      <>
        <p>
          Some Services are free to evaluate; others require a paid
          subscription or contract. Pricing, billing terms, and renewal terms
          will be specified in the applicable order form or agreement. Fees
          are non-refundable except as required by law or expressly stated in
          a written agreement.
        </p>
      </>
    ),
  },
  {
    id: 'termination',
    heading: 'Termination',
    body: (
      <>
        <p>
          You may stop using the Services at any time. We may suspend or
          terminate your access if you violate these Terms, if we discontinue
          a Service, or as otherwise required by law. Sections that by their
          nature should survive termination (including Intellectual Property,
          Disclaimers, Limitation of Liability, and Indemnification) will
          survive.
        </p>
      </>
    ),
  },
  {
    id: 'warranties',
    heading: 'Disclaimers',
    body: (
      <>
        <p>
          THE SERVICES ARE PROVIDED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS.
          ROSHAN AI DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
          IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
          PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICES
          WILL BE ERROR-FREE OR UNINTERRUPTED, OR THAT OUTPUTS WILL BE
          CLINICALLY ACCURATE IN EVERY CASE.
        </p>
      </>
    ),
  },
  {
    id: 'liability',
    heading: 'Limitation of liability',
    body: (
      <>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, ROSHAN AI WILL NOT BE LIABLE
          FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
          DAMAGES, OR FOR LOST PROFITS, REVENUES, OR DATA, ARISING FROM YOUR
          USE OF THE SERVICES. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT
          OF OR RELATING TO THE SERVICES WILL NOT EXCEED THE GREATER OF (A)
          THE FEES YOU PAID TO US IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR
          (B) ONE HUNDRED U.S. DOLLARS.
        </p>
      </>
    ),
  },
  {
    id: 'indemnification',
    heading: 'Indemnification',
    body: (
      <>
        <p>
          You agree to defend, indemnify, and hold harmless Roshan AI from any
          third-party claim, loss, or expense (including reasonable attorneys'
          fees) arising from your violation of these Terms, your misuse of the
          Services, or your violation of applicable law.
        </p>
      </>
    ),
  },
  {
    id: 'governing-law',
    heading: 'Governing law and disputes',
    body: (
      <>
        <p>
          These Terms are governed by the laws of the State of Arizona,
          without regard to its conflict-of-laws principles. Any dispute
          arising out of or relating to these Terms will be resolved in the
          state or federal courts located in Maricopa County, Arizona, and
          the parties consent to personal jurisdiction in those courts.
        </p>
      </>
    ),
  },
  {
    id: 'changes',
    heading: 'Changes to these Terms',
    body: (
      <>
        <p>
          We may update these Terms from time to time. If the changes are
          material, we will take reasonable steps to notify you (for example,
          by email or a prominent notice on the site). Your continued use of
          the Services after the changes become effective constitutes
          acceptance of the updated Terms.
        </p>
      </>
    ),
  },
  {
    id: 'contact',
    heading: 'Contact us',
    body: (
      <>
        <p>
          Questions about these Terms? Email{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-accent hover:underline">
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </>
    ),
  },
];

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service — Roshan AI</title>
        <meta
          name="description"
          content="The terms governing use of the Roshan AI website and the ShifaMind platform."
        />
        <meta name="robots" content="noindex" />
        <link rel="canonical" href="https://roshan-ai.com/legal/terms" />
      </Head>
      <LegalLayout
        eyebrow="Legal · Terms"
        title="Terms of Service"
        effectiveDate="2026-01-01"
        intro={
          <p>
            These Terms govern your use of Roshan AI's website and the
            ShifaMind platform. They cover the basics: who can use the
            Services, what you can and can't do, and how we handle the things
            you submit.
          </p>
        }
        sections={sections}
      />
    </>
  );
}
